spring:

  mvc:
    log-request-details: true

  devtools:
    add-properties: true

  ai:
    openai:
      api-key: "insert key here"

    ollama:
      base-url: http://localhost:11434
      settings:
#        modelString: # NOTE: very slow - but very detailed
#          "deepseek-r1:1.5b"
        model: llama3

logging:
  level:
    web: debug
    sql: debug

server:
  port: 2962