spring:
  application:
    name: @pom.artifactId@
    version: @release.version@

  devtools:
    add-properties: false

  ai:
    openai:
      api-key: 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

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
      init:
        pull-model-strategy: WHEN_MISSING
        embedding:
          include: true

logging:
  level:
    root: info
    web: info
    sql: info

server:
  port: 8080
  servlet:
    context-path: /AI-Test