spring:
  application:
    name: @pom.artifactId@
    version: @release.version@

  devtools:
    add-properties: false

  jpa:
    open-in-view: false

  ai:
    openai:
      api-key: "insert key here"

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3

      init:
        pull-model-strategy: WHEN_MISSING
        max-retries: 2
#        embedding: # This is not used in this application yet.
#          include: true # read this to see why -> https://docs.spring.io/spring-ai/reference/api/embeddings.html
        chat:
          include: true
      settings:
        model: llama3
        temperature: 0.4

logging:
  level:
    root: info
    web: info
    sql: info

server:
  port: 8080
  servlet:
    context-path: /AI-Test