spring:

  mvc:
    log-request-details: true

  devtools:
    add-properties: true

  ai:
    openai:
      api-key: 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

    ollama:
      base-url: http://localhost:11434

logging:
  level:
    web: debug
    sql: debug

server:
  port: 2962